### ISSUE TITLE
Mau tanya bg

### ISSUE THREAD

**Issue by turtleion** [Fastering18/OSeraX#1]
Izin mau tanya bg, itu osnya base nya dari apa? Dan itu os nya udah ada driver mouse, keyboard, dan ethernetnya?

**Comment by Fastering18** [comment]
> osnya base nya dari apa? 

Basis Unix OS.
https://id.m.wikipedia.org/wiki/Unix


> os nya udah ada driver mouse, keyboard, dan ethernetnya?

Belum, masih tahap mikrokernel. Hanya support keyboard.

<hr>
sorry ya bg... baru respon 😅🙏
