### ISSUE TITLE
g bisa di compile?

### ISSUE THREAD

**Issue by ChronicleDevs** [Fastering18/OSeraX#2]
ld: ld: DWARF error: invalid or unhandled FORM value: 0x22
./drivers/cpu/idt.o:(.bss+0x1820): multiple definition of `int_table'; ld: DWARF error: invalid or unhandled FORM value: 0x22
./kernel/kernel.o:(.bss+0x8): first defined here
ld: ./drivers/cpu/sidt.o: in function `int_table':
drivers/cpu/sidt.s:(.data+0x0): multiple definition of `int_table'; ./kernel/kernel.o:(.bss+0x8): first defined here
ld: warning: ./drivers/cpu/sidt.o: missing .note.GNU-stack section implies executable stack
ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
make[1]: *** [GNUmakefile:85: kernel/kernel.elf] Error 1
make[1]: Leaving directory '/home/churachelle/OSeKAI/src'
make: *** [GNUmakefile:49: kernel] Error 2
                                            

muncul error itu saat compile.
setiap compile pasti ada error itu, udh gw coba di Ubuntu, Kali, Arch sama aja

ada solusi?

Mungkin ada versi yg udh dicompile jdi iso?

**Comment by Fastering18** [comment]
kayaknya itu ada obj file yang belum dihapus pas run `make`  
coba run `make clean && make` lalu run bash di `run.sh`  
👉 kalo belum work coba clone commit terbaru.

-> ISO file bisa download di  [releases](https://github.com/Fastering18/OSeKAI/releases/tag/preview-1)  
-> Cek juga dokumentasi baru [OSeKAI](https://github.com/Fastering18/OSeKAI/tree/work-c-limine)
